item_teleport_city = class({})
item_teleport_spawn = class({})
item_teleport_boss1 = class({})
item_teleport_boss2 = class({})
item_teleport_boss3 = class({})
item_teleport_boss4 = class({})
item_teleport_boss5 = class({})

teleport_city = class({})
teleport_spawn = class({})
teleport_boss1 = class({})
teleport_boss2 = class({})
teleport_boss3 = class({})
teleport_boss4 = class({})
teleport_boss5 = class({})